config/routes.rb
Rails.application.routes.draw do

  resources :sqanswers
  resources :sqresults
  get 'presence/update'
  get 'lesson' => 'exercises#lesson'
  post 'lesson' => 'exercises#lesson'
  post 'new_result' => 'result#create'
  
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'
  resources :sidequests
  root 'session#index'
  resources :answers
  resources :messages
  resources :teachers do
    resources :groups, shallow: true do
      resources :students
    end
    resources :exercises, shallow: true
  end

  get 'show_exe' => 'exercises#show_exe'
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'
  put 'sqanswer_update' => 'sidequests#sqanswer_update'
  put 'classes_update' => 'classescalendar#update'
  put 'presences_update' => 'presence#update'
  get 'student/edit' => 'students#edit'
  get 'faq' => 'students#faq'
  patch 'student/solution' => 'students#solution'
  get 'student/challenge' =>'students#challenge'
  get 'student/chosechallenge' =>'students#chosechallenge'
  get 'student/challengeodp' =>'students#challengeodp'
  get 'student/challengeodp2' =>'students#challengeodp2'
  get 'student/challengeinbox' =>'students#challengeinbox'
  post 'student/challengeconfirm' =>'students#challengeconfirm'
  post 'student/challengeconfirm2' =>'students#challengeconfirm2'
  get 'challenges' => 'challenge#index'
  post 'challenge_win' => 'challenge#win'
  post 'challenge_draw' => 'challenge#draw'
  get 'student/surender' =>  'students#surender'
  get 'student/studentprofile' =>  'students#studentprofile'
  get 'student/hppotion' =>  'students#hppotion'
  get 'contact', to: 'my_mail#new', as: 'contact'
  post 'contact', to: 'my_mail#create'
  get 'settings' => 'students#settings'
end

app/models/message.rb
class Message < ActiveRecord::Base
    belongs_to :teacher
    belongs_to :student
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]
  before_action :logged_user, only: [:index, :new, :destroy,:edit, :update, :create]
  
  # GET /wiadomoscis
  # GET /wiadomoscis.json
  def index
    if logged_as_student?
        @messages = Message.where(student_id: session[:user_id], direction: "0").order("created_at DESC")
    end
    if logged_as_teacher?
       @messages = Message.where(teacher_id: session[:user_id], direction: "1").order("created_at DESC")
    end
  end

  # GET /wiadomoscis/1
  # GET /wiadomoscis/1.json
  
  def show
    @message =Message.find(params[:id])
    @student = Student.find(@message.student_id)
    if logged_as_student? && @message.direction == 0
      @message.read = true
      @message.save
    end
    if logged_as_teacher? && @message.direction == 1
      @message.read = true
      @message.save
    end
  end

  # GET /wiadomoscis/new
  def new
    @message = Message.new
  end

  # GET /wiadomoscis/1/edit
  def edit
  end

  # POST /wiadomoscis
  # POST /wiadomoscis.json
  def create
     if logged_as_student?
        createstu
     end
     if logged_as_teacher?
        if params[:message][:id]!=nil
          createwy
        end
        if params[:message][:idgrupy]!=nil
          createwy2
        end
     end
  end
  
  
  
  
  # PATCH/PUT /wiadomoscis/1
  # PATCH/PUT /wiadomoscis/1.json
  def update
    respond_to do |format|
      if@message.update(wiadomosci_params)
        format.html { redirect_to@message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location:@message }
      else
        format.html { render :edit }
        format.json { render json:@message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wiadomoscis/1
  # DELETE /wiadomoscis/1.json
  def destroy
   @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def createstu
    student=Student.find_by(id: session[:user_id])
    gr=Group.find_by(student.group_id)
   @message = Message.new(message_params)
   @message.student_id=session[:user_id]
   @message.teacher_id=gr.teacher_id
   @message.direction="1"
   @message.read= false
      respond_to do |format|
        if @message.save
          format.html { redirect_to@message, notice: 'Message was successfully created.' }
          format.json { render :index, status: :created, location:@message }
        else
          format.html { render :new }
          format.json { render json:@message.errors, status: :unprocessable_entity }
        end
      end
  end
    def createwy 
     @message = Message.new(message_params)
     @message.teacher_id=session[:user_id]
     @message.student_id=params[:message][:id]
     @message.direction="0"
     @message.read =false
        respond_to do |format|
          if @message.save
            format.html { redirect_to @message, notice: 'Message was successfully created.' }
            format.json { render :index, status: :created, location: @message }
          else
            format.html { render :new }
            format.json { render json: @message.errors, status: :unprocessable_entity }
          end
        end
    end
    def createwy2 
     students=Student.where(group_id: params[:message][:idgrupy])
     students.each do |student|
      @message = Message.new(message_params)
      @message.teacher_id=session[:user_id]
      @message.student_id=student.id
      @message.direction="0"
      @message.read =false
      @message.save     
     end
        respond_to do |format|
          if @message.save
            format.html { redirect_to @message, notice: 'Message was successfully created.' }
            format.json { render :index, status: :created, location: @message }
          else
            format.html { render :new }
            format.json { render json: @message.errors, status: :unprocessable_entity }
          end
        end
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:subject, :content)
    end
    def logged_user
      redirect_to root_url unless logged_as_student? || logged_as_teacher?
    end
    
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<div class ="bg_message">
  
  <div class="student_message_title">
        <h1>Wiadomości</h1>
    </div>
    <%= link_to messages_path(session[:user_id]) do%>
      <div class="backto_msg tooltip">
        <span>Kliknij aby wrócić do skrzynki</span>
      </div>
    <% end %>
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this wiadomosci from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="student_new_message_content">
    <%= f.label "temat" %><br>
    <%= f.text_field "subject" %><br><br>
    <%= f.label "treść" %><br>
    <%= f.text_area :content, size: "60x5" %><br>
  
    <div class="actions btn_send">
      <%= f.submit "Wyślij"%>
    </div>
  </div>
<% end %>
</div>

app/views/messages/_form1.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <%= form_for(@message) do |f| %>
      <% if @message.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@message.errors.count, "error") %> prohibited this @message from being saved:</h2>
    
          <ul>
          <% @message.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <h1>Wiadomość do studenta</h1>
      <%= f.hidden_field "id", :value => params[:iid] %>
      <div class="form-group">
        <%= f.label "temat" %>
        <%= f.text_field "subject", :class =>"form-control",:placeholder =>"Temat Wiadomości" %>
      </div>
      <div class="form-group">
        <%= f.label "Treść" %><br>
        <%= f.text_area :content, :class =>"form-control", :rows =>"5",:placeholder =>"Tekst Wiadomości" %>
      </div>
      <%= f.submit "Wyślij", :class =>"btn btn-primary btn-block"%>
    <% end %>
  </div>
</div>

app/views/messages/_form2.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <%= form_for(@message) do |f| %>
      <% if @message.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@message.errors.count, "error") %> prohibited this @message from being saved:</h2>
    
          <ul>
          <% @message.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <h1>Wiadomość do grupy</h1>
      <%= f.hidden_field "idgrupy", :value => params[:idg] %>
      <div class="form-group">
        <%= f.label "temat" %>
        <%= f.text_field "subject", :class =>"form-control",:placeholder =>"Temat Wiadomości" %>
      </div>
      <div class="form-group">
        <%= f.label "Treść" %><br>
        <%= f.text_area :content, :class =>"form-control", :rows =>"5",:placeholder =>"Tekst Wiadomości" %>
      </div>
      <%= f.submit "Wyślij", :class =>"btn btn-primary btn-block"%>
    <% end %>
  </div>
</div>

app/views/messages/edit.html.erb
<h1>Editing Wiadomosci</h1>

<%= render 'form' %>

<%= link_to 'Show', @wiadomosci %> |
<%= link_to 'Back', wiadomoscis_path %>

app/views/messages/index.html.erb
<% if logged_as_student? %>
<div class="bg_message">
    
    <div class="student_message_title">
        <h1>Wiadomości</h1>
    </div>
    <%= link_to student_path(session[:user_id]) do%>
      <div class="back_msg tooltip">
        <span>Kliknij aby przejść do mapy świata</span>
      </div>
    <% end %>
    <div class="student_new_message">
      <%= link_to new_message_path(session[:user_id]) do%>
          <span>zadaj pytanie wykładowcy</span>
      <%end%>
    </div>
<div class="student_message_content">
  <table>
      <thead>
        <tr>
          <th>Nr.</th>
          <th>Temat</th>
        </tr>
      </thead>
    <% i=0%>
    <tbody>

      <% @messages.each do |message| %>
      <tr>
          <td><%= i=1+i %></td>
          <%if message.read%>
          <td><%= message.subject %></td>
          <%else%>
          <td><strong><%=message.subject%></strong></td>
          <%end%>
          <td class="table_button"><%= link_to 'Otwórz', message_path(:id => message.id) %></td>
          <td class="table_button"><%= link_to 'Usuń', message, method: :delete, data: { confirm: 'Czy napewno chcesz usunąć wiadomość?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
</div>

<%else%>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <center><h1>Wiadomości</h1></center>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nr</th>
          <th>Temat</th>
          <th colspan="2"></th>
        </tr>
      </thead>
     <% i=0%>
      <tbody>
        <% @messages.each do |message| %>
          <tr>
            <td><%= i=1+i %></td>
            <%if message.read%>
              <td><%= message.subject %></td>
            <%else%>
              <td><strong><%=message.subject%></strong></td>
            <%end%>
            <td><%= link_to 'Otworz', message_path(:id => message.id), :class =>"btn btn-primary" %></td>
            <td><%= link_to 'Usuń', message, method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć wiadomość?' }, :class =>"btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% end  %>

app/views/messages/new.html.erb
<% if logged_as_student? %>
    <%= render 'form' %>
<%end %>
<% if logged_as_teacher? %>
    <% if params[:iid]!=nil %>
        <%= render 'form1' %>
    <% end %>
    <% if params[:idg]!=nil %>
        <%= render 'form2' %>
    <% end %>
<%end %>

app/views/messages/show.html.erb
<% if logged_as_student? %>
<div class="bg_message">
    <div class="student_message_title">
        <h1>Wiadomości</h1>
    </div>
    <%= link_to messages_path(session[:user_id]) do%>
      <div class="backto_msg tooltip">
        <span>Kliknij aby wrócić do skrzynki</span>
      </div>
    <% end %>
    <div class="student_message_show">
    <h3>temat:</h3> 
    <p><%= Message.find_by(id: params[:id]).subject %></p>
    <h3>treść:</h3> 
    <p><%= Message.find_by(id: params[:id]).content %></p>
    
   </div>
   <div class="student_new_message">
        <%= link_to new_message_path(session[:user_id]) do%>
          <span>zadaj pytanie wykładowcy</span>
        <%end%>
    </div>
</div> 
<% else %>
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <center><h1>Wiadomości</h1></center>
        <h3>Nadwca</h3>
        <p><%=@student.name%> <%=@student.lastname%></p>
        <h3>Temat</h3>
        <p><%= Message.find_by(id: params[:id]).subject %></p>
        <h3>Treść</h3>
        <p><%= Message.find_by(id: params[:id]).content %></p>
        <% sid= Message.find(params[:id]) %>
        <center><%= link_to 'Odpowiedz', new_message_path(:iid => sid.student_id ), :class =>"btn btn-primary" %></center>
      </div>
    </div>
<% end %>    