config/routes.rb
Rails.application.routes.draw do

  resources :sqanswers
  resources :sqresults
  get 'presence/update'
  get 'lesson' => 'exercises#lesson'
  post 'lesson' => 'exercises#lesson'
  post 'new_result' => 'result#create'
  
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'
  resources :sidequests
  root 'session#index'
  resources :answers
  resources :messages
  resources :teachers do
    resources :groups, shallow: true do
      resources :students
    end
    resources :exercises, shallow: true
  end

  get 'show_exe' => 'exercises#show_exe'
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'
  put 'sqanswer_update' => 'sidequests#sqanswer_update'
  put 'classes_update' => 'classescalendar#update'
  put 'presences_update' => 'presence#update'
  get 'student/edit' => 'students#edit'
  get 'faq' => 'students#faq'
  patch 'student/solution' => 'students#solution'
  get 'student/challenge' =>'students#challenge'
  get 'student/chosechallenge' =>'students#chosechallenge'
  get 'student/challengeodp' =>'students#challengeodp'
  get 'student/challengeodp2' =>'students#challengeodp2'
  get 'student/challengeinbox' =>'students#challengeinbox'
  post 'student/challengeconfirm' =>'students#challengeconfirm'
  post 'student/challengeconfirm2' =>'students#challengeconfirm2'
  get 'challenges' => 'challenge#index'
  post 'challenge_win' => 'challenge#win'
  post 'challenge_draw' => 'challenge#draw'
  get 'student/surender' =>  'students#surender'
  get 'student/studentprofile' =>  'students#studentprofile'
  get 'student/hppotion' =>  'students#hppotion'
  get 'contact', to: 'my_mail#new', as: 'contact'
  post 'contact', to: 'my_mail#create'
  get 'settings' => 'students#settings'
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :group
  has_one :teacher, through: :group
  has_many :presences, dependent: :destroy
  has_one :progre, dependent: :destroy
  has_many :drawnexercises, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :awarded_medals, dependent: :destroy
  has_secure_password
  before_save :downcase_email
  

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }, allow_nil:true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil:true 
  validates :album_number, :numericality => {:only_integer => true}
  def admit_medal(medal)
    awarded_medals.create(medal_id: medal)
    self.progre.points += Medal.find_by(id: medal).value
    self.progre.save
  end
  def take_medal(medal)
    awarded_medals.find_by(medal_id: medal).destroy
  end
  def has_medal?(medal)
    awarded_medals.exists?(medal_id: medal)
  end
  
    private
      def downcase_email
        if !self.email.nil?
          self.email = email.downcase
        end
      end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :correct_student, only: :show
  before_action :correct_teacher, only: [:create, :destroy]
  
  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

    def studentprofile
      if logged_as_student?
       @pkt=Result.where(student_id: session[:user_id])
       @medals=Student.find(session[:user_id]).awarded_medals.all
       @sidequests=Sqresult.where(student_id: session[:user_id])
       @prezences=Presence.where(student_id: session[:user_id])
      end
      if logged_as_teacher?
       @student =Student.find(params[:format])
       @pkt=Result.where(student_id: @student.id)
       @medals=AwardedMedal.where(student_id: @student.id)
       @sidequests=Sqresult.where(student_id: @student.id)
       @prezences=Presence.where(student_id: @student.id)
      end
    end
    
    
    def show
        @student = Student.find_by(login: session[:login])
        @progr=Progre.find_by(student_id: session[:user_id])
    end
  
    def hppotion
      pr = Progre.find_by(student_id: session[:user_id])
      if pr.hp <90 && pr.points>=30 
        hpnowe=pr.hp+20
        if hpnowe>100
          hpnowe=100
        end
        pr.update_column(:hp , hpnowe)
        pr.update_column(:points, pr.points-30)
      end
      if pr.save
        redirect_to :back
      end
    end
    
    def solution
        idzadania=Drawnexercise.find_by(student_id: session[:user_id], level: params[:answer][:level], number: params[:answer][:number])
        tre=Exercise.find_by(id: idzadania.exercise_id)
        @zad=Answer.find_by(student_id: session[:user_id], exercise_id: tre.id )
        @zad.update_column(:solution, params[:answer][:solution])
        @zad.update_column(:reward , params[:answer][:reward])
        if @zad.save
          redirect_to :back
        end
    end
 
  def create
    group = Group.find(params[:group_id])
    @student = group.students.create(new_student_params)
    @student.login = params[:student][:album_number]
    @student.password_digest = BCrypt::Password.create(params[:student][:album_number])
    respond_to do |format|
    if @student.save
            for i in 1..6
              presence = Presence.new(:student_id => @student.id, :classes_number => i, :present => true)
              presence.save
            end
        progrs = Progre.new(student_id: @student.id, points: 0, hp: 100, gained_points: 0, total: 0, lvl: 1)
        progrs.save
        format.html{redirect_to :back, notice: 'Stworzono studenta'}
    else
        format.html { redirect_to :back }
        format.json { render json: @student.errors, status: :unprocessable_entity }
    end
    end
  end

  def update
    respond_to do |format|
      if logged_as_student?
        @student.autenticated = true
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
      end
      
      if logged_as_teacher?
        if @student.update(student_params)
          format.html { redirect_to :back, notice: 'Student was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end
  end


  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 
  def settings
  end
  
  
  #################################################################3
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
     @student = Student.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:login, :password, :email, :name, :lastname)
    end
    def new_student_params
      params.require(:student).permit(:album_number)
    end
    
    def correct_student
        set_student
        redirect_to root_url unless @student == Student.find_by(login: session[:login])
    end
    def correct_teacher
      redirect_to root_url unless Teacher.find_by(login: current_user_login) 
    end
    
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
   
end

app/views/students/_form.html.erb
<% if logged_as_student? %>
<div class="bg_login">
  <img class="bg" src="/assets/sign_in/bg_login2.jpg">
    <div class="form_login_first">
          <%= form_for(@student) do |f| %>
            <% if @student.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>
                <ul>
                <% @student.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
          
            <div class="field">
              <%= f.label :login,"Login", :class =>"label_font"%>
              <%=f.text_field :login, :class =>"input_login"%>
            </div>
            <div class="field">
              <%=f.label :password, "Hasło" , :class =>"label_font"%>
              <%=f.password_field :password, :class =>"input_password"%>
            </div>
            <div class="field">
              <%= f.label :password_confirmation, "Potwierdź Hasło" , :class =>"label_font" %>
              <%= f.password_field :password_confirmation, :class =>"input_password" %>
            </div>
            <div class="field">
              <%= f.label :email,"E-mail", :class =>"label_font"%><br>
              <%= f.text_field :email, :class =>"input_email" %>
            </div>
            <div class="field">
              <%= f.label :Imie,"Imię", :class =>"label_font"%><br>
              <%= f.text_field :name, :class =>"input_name" %>
            </div>
            <div class="field">
              <%= f.label :Nazwisko,"Nazwisko", :class =>"label_font"%><br>
              <%= f.text_field :lastname, :class =>"input_lastname"%>
            </div>
            <div class="actions">
              <%= f.submit "zmień", :class =>"button_update label_font"%>
            </div>
            <div class ="log_out_btn label_font" >
              <%= link_to "Wyloguj", logout_path, method: "delete"%>
            </div>
          <% end %>
      </div>
</div>
<% elsif logged_as_teacher? %>
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <h1>Zmień dane studenta</h1>
      <%= form_for @student do |f| %>
        <% if @student.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>
              <ul>
                <% @student.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :login, "Login"%>
          <%=f.text_field :login, :class =>"form-control"%>
        </div>
        <div >
          <%=f.label :password, "Hasło"%>
          <%=f.password_field :password, :class =>"form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "Potwierdź Hasło" %>
          <%= f.password_field :password_confirmation, :class =>"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email, "E-mail"%>
          <%= f.text_field :email, :class =>"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :Imie, "Imię"%>
          <%= f.text_field :name, :class =>"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :Nazwisko, "Nazwisko"%>
          <%= f.text_field :lastname, :class =>"form-control"%>
        </div>
        <%= f.submit "Zmień", :class =>"btn btn-primary btn-block"%>
      <% end %>
    </div>
  </div>
<% end%>

app/views/students/_panel.html.erb
<%
@student = Student.find_by(id: session[:user_id])
@progr=Progre.find_by(student_id: session[:user_id])

    gr= Student.find(session[:user_id])
    progresy=Progre.order(points: :desc)
    i=1
    k=0
    progresy.each do |pr|
       k=k+1
        if pr.student_id==session[:user_id]
            @ran=i
            @j=k
        end
        gru=Student.find(pr.student_id)
        if gru.group_id==gr.group_id
            i=i+1
        end
    end
verification
%>


<div class="student_header">
        <div class="student_avatar">
            <%= link_to student_studentprofile_path(session[:user_id], :results => "1"), :class => "tooltip" do %>
                <div class="student_name">
                    <h2><%= @student.name %></h2>
                </div>
                <div class="student_lastname">
                    <h2><%= @student.lastname %></h2>
                </div>
                <span>Kliknij, aby przejść do profilu gracza i uzyskać szczegółowe informacje o koncie.</span>
            <% end %>
        </div>
    <div class="student_statistic">
        <div>
            <div class="student_hp">
                <h4>hp: <%=@progr.hp %>/100</h4>
            </div>
            <div class="student_pustak"></div>
            <div class="student_hp_potion">
                <%= link_to student_hppotion_path(session[:user_id]), :class =>"tooltip" do %>
                    <h4>+20 hp</h4>  
                    <img src="/assets/student/hp_potion.png" alt="">
                    <span>Kup miksturę, aby się uleczyć:<br>
                        + 20 hp,<br>
                        - 20 pkt rankingowych,
                        <br>aby użyc musisz mieć mniej niż 90 hp.
                    </span>
                <% end %>
            </div>
        </div>
        <script>
            $(document).ready(function() {
                var hp = <%= @progr.hp%>;
                var exp = <%= @progr.gained_points %>*100/<%=@progr.total%>
                $('#progress_hp_bar').css("width",hp + "%");
                $('#progress_exp_bar').css("width",exp + "%");
            });
        </script>
        <div class="progress_hp">
            <div id="progress_hp_bar" class="progress_hp_bar"></div>
        </div>
        <div>
            <div class="student_exp">
                <h4>exp: <%=@progr.gained_points%>/<%=@progr.total%></h4>
            </div>
        </div>
        <div class="progress_exp">
            <div id="progress_exp_bar" class="progress_exp_bar"></div>
        </div>
        <div>
            <div class="student_lvl tooltip">
                <h4>Poziom: <%=@progr.lvl %></h4>
                <span>Poziom odpawiada numerze lekcji, która się odbywa.</span>
            </div>
            <div class="student_pustak"></div>
            <div class="student_pkt_rank tooltip">
                <h4>pkt rankingowe: <%=@progr.points%></h4>
                <span>Punkty rankingowe zdobywasz za wykonywanie zadań.
                Zbierz jak najwięcej, aby uzyskać lepsze miejsce w rankingu.
                Możesz je wydać na zakup mikstury leczniczej</span>
            </div>
        </div>
        <div class="student_rank">
            <div class="student_rank_world">
                <div class="student_bg_rank_world">
                    <h1><%= @j %></h1>
                </div>
                <span>ranking<br>światowy</span>
            </div>
            <div class="student_pustak"></div>
            <div class="student_rank_group">
                <div class="student_bg_rank_group">
                    <h1><%= @ran %></h1>
                </div>
                <span>ranking<br>grupowy</span>
            </div>
        </div>
    </div>
    <div class="student_other">
        <div class="student_log_out">
            <%= link_to logout_path, method: "delete" do %>
                <div class="log_out tooltip">
                    <img src="/assets/student/student_logout.png" alt="">
                    <span>Wyloguj</span>
                </div>
            <% end %>
        </div>
        <div class="student_settings">
            <%= link_to settings_path do %>
                <div class="settings tooltip">
                    <%= image_tag("/assets/student/settings.png")%>
                    <span>Ustawienia</span>
                </div>
            <% end %>
        </div>
        <div class="student_message">
            <%= link_to messages_path(session[:user_id]) do %>
                <% if Message.where(student_id: session[:user_id], direction: "0", read: false).count > 0 %>
                    <div class="new_message tooltip">
                        <%=image_tag("/assets/student/new_message.png")%>
                        <span>Masz <%=Message.where(student_id: session[:user_id], direction: "0", read: false).count%> nieprzeczytanych wiadomości </span>
                    </div>
                <%else%>
                    <div class="message tooltip">
                        <%=image_tag("/assets/student/message.png")%>
                        
                        <span>Nie masz nowych wiadomości</span>
                    </div>
                <% end %>
            <% end %>
        </div>
        <div class="student_challenge">
            <%= link_to sidequests_path do%>
            <%gr=Group.find_by(id: @student.group_id)%>
                <%if Sidequest.where(level: @progr.lvl, teacher_id: gr.teacher_id).count == Sqanswer.where(student_id: session[:user_id]).count%>
                    <div class="challenge tooltip">
                        <%= image_tag("/assets/student/challenge.png") %>
                        <span>Nie masz nowych wyzwań</span>
                    </div>
                <%else%>
                    <div class="new_challange tooltip">
                        <%= image_tag("/assets/student/new_challenge.png") %>
                        <span>Masz <%=Sidequest.where(level: @progr.lvl, teacher_id: gr.teacher_id).count - Sqanswer.where(student_id: session[:user_id]).count%> nowych wyzwań</span>
                    </div>
                <%end%>
            <% end %>
        </div>
    </div>
</div>

<!--<div>-->
<!--    <br>---------------------------------------------------------------------------------------------------------------</br>-->
<!--    <br>| <%= link_to "Mapa świata", student_path(session[:user_id]) %> | -->

<!--    <%= link_to "Edytuj profil", edit_student_path(session[:user_id]) %> | -->
<!--    <%= link_to "FAQ", faq_path() %> |<br><br>-->
<!--    <%= link_to "Edytuj profil", edit_student_path(session[:user_id]) %> | <br><br>-->

<!--</div>                       -->

app/views/students/challenge.html.erb
<%= render "panel" %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
 <% i=0%>
  <tbody>
    <% @idgru.each do |stud| %>
      <tr>
        <td><%= i=1+i %></td>
        <td><%= stud.name %></td>
        <td><%= stud.lastname %></td>
        <td><%= link_to "wybierz zadanie", student_chosechallenge_path(:idst => stud.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/challengeinbox.html.erb
<%= render "panel" %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
 <% i=0%>
  <tbody>
    <% @wyzwania.each do |wyzwanie| %>
      <tr>
          <% if wyzwanie.status==0 %>
            <td><%= i=1+i %></td>
            <td><%= Student.find(wyzwanie.challenger_id).name %></td>
            <td><%= Student.find(wyzwanie.challenger_id).lastname %></td>
            <td><%= link_to "Rozwiaż", student_challengeodp2_path(:idwyzwania => wyzwanie.id)%></td>
            <td><%= link_to "Oddaj walkower", student_surender_path(:idwyzwania => wyzwanie.id)%></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/challengeodp.html.erb
<%= render "panel" %>
<br><%=Exercise.find_by(id: params[:zada]).content%></br>
<%= form_for :zad, url: {action: "challengeconfirm"} do |f| %>
  <%= f.hidden_field "zadanie", :value => params[:zada] %>
  <%= f.hidden_field "wyzwany", :value => params[:idst] %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %> 

app/views/students/challengeodp2.html.erb
<%= render "panel" %>
<br><%=Sidequest.find(params[:idwyzwania]).content%></br>
<%= form_for :zad, url: {action: "challengeconfirm2"} do |f| %>
  <%= f.hidden_field "wyzwanie", :value => params[:idwyzwania] %>
  <%= f.text_area :odp, size: "60x5" %><br>
  <%= f.submit "Wyślij" %></br>
<% end %> 

app/views/students/chosechallenge.html.erb
<%= render "panel" %>
<%= link_to "Mapa świata", student_path(session[:user_id]) %>
<br>Wyzywasz <%= @wyzwany.name %> <%= @wyzwany.lastname %> na pojedynek</br>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
 <% i=0%>
  <tbody>
    <% @zadania.each do |zad| %>
      <tr>
        <td><%= i=1+i %></td>
        <td><%= zad.content %></td>
        <td><%= link_to "sprawdz go", student_challengeodp_path(:idst => @wyzwany.id, :zada => zad.id)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/faq.html.erb
<div class="bg_profil">
    <div class="student_message_title">
        <h1>FAQ</h1>
    </div>
    <%= link_to settings_path do%>
      <div class="backto_msg tooltip">
        <span>Kliknij aby wrócić do ustawień</span>
      </div>
    <% end %>
    <div class="faq_content">
        <h3>Tutaj znajdziesz wszystkie potrzebne wskazówki jak korzystać z serwisu<h3>
        <h4>Mapa świata</h4>
        <p>Wczuj się w rolę odkrywcy a to jest twoja mapa. Kolejne jej elementy będziesz odkrywać przy kolejnych zajęciach, 
        a ich daty są ustalane przez twojego wykładowce. Każdy punkt na mapie odpowiada jednym zajęciom, są to krainy, 
        w których znajdują się zadania na które musisz udzielić odpowiedzi</p>
        <h4>Rozwiązywanie zadań</h4>
        <p>Na mapach krainy rozmieszczone jest pięć zadań. Przy treści zadania widnieją podpowiedzi z których możesz skorzystać. 
        Każde zadanie możesz wysyłać wielokrotnie, jednak do sprawdzenia trafi ostatnie rozwiązanie i musisz pamiętać 
        by mieścić się w terminach. </p>
        <h4>W razie problemów</h4>
        <p>W razie problemów z zadaniem możesz skożystać z komunikatora aby napsać wiadomość do swojego wykładowcy, 
        na pewno chętnie rozwieje twoje wątpliwości.</p>
        <h4>Praca po godzinach</h4>
        <p>Dodatkowe punkty można zdobyć utrwalając wiedzę zdobytą na zajęciach w dodatkowych zadaniach. Udział w nich
        nie jest obowiązkowy.</p>
        <h4>Panel Użytkownika</h4>
        <p>W panelu widnieją informacje twojego postępu. 
        Pasek hp: życie tracisz za nieobecności, rozwiązania które nie uzyskały maksymalnej liczby punktów oraz za brak rozzwiązań.
        Pasek exp: dzięki niemu możesz zaobsrerwować ile punktów Ci brakuje by być najlepszym.
        Punkty rankingowe: to suma wyników rozwiązań zadań.
        Pozycja w rankingu światowym oraz grupowym. 
        Więcej szczegółowych informacji na temat postępu znajdziesz klikając na avatar.
        Podczas nauki jak na wojnie... może zabraknąć ci życia, dlatego też przygotowaliśmy dla ciebie leczniczą mimlsturę. 
        Możesz ją wymienić za 20 punktów rankingowych. Musisz być czujny bo jeśli pasek życia spadnie do zera stracisz jedną czwartą
        zdobytych punktów. Nasz zespół trzyma kciuki żeby do tego nie doszło. Powodzenia!</p>
        
    </div>
</div>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Password digest</th>
      <th>Email</th>
      <th>Name</th>
      <th>Lastname</th>
      <th>album_number</th>
      <th>Authenticated</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.login %></td>
        <td><%= student.password_digest %></td>
        <td><%= student.email %></td>
        <td><%= student.name %></td>
        <td><%= student.lastname %></td>
        <td><%= student.album_number %></td>
        <td><%= student.authenticated %></td>
        <td><%= student.group %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/settings.html.erb
<div class="bg_profil">
    <div class="student_message_title">
        <h1>Ustawienia</h1>
    </div>
    <%= link_to student_path(session[:user_id]) do%>
      <div class="back_msg tooltip">
        <span>Kliknij aby przejść do mapy świata</span>
      </div>
    <% end %>
    <nav class="navbar_student_settings"style="width: 30%">
        <ul>
            <li><%= link_to "Zgłoś błąd", contact_path %></li>
            <li><%= link_to "FAQ", faq_path %></li>
            <li><%= link_to "Zmień hasło", edit_student_path(session[:user_id]) %></li>
            
        </ul>
    </nav>
</div>