config/routes.rb
Rails.application.routes.draw do

  resources :sqanswers
  resources :sqresults
  get 'presence/update'
  get 'lesson' => 'exercises#lesson'
  post 'lesson' => 'exercises#lesson'
  post 'new_result' => 'result#create'
  
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'
  resources :sidequests
  root 'session#index'
  resources :answers
  resources :messages
  resources :teachers do
    resources :groups, shallow: true do
      resources :students
    end
    resources :exercises, shallow: true
  end

  get 'show_exe' => 'exercises#show_exe'
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'
  put 'sqanswer_update' => 'sidequests#sqanswer_update'
  put 'classes_update' => 'classescalendar#update'
  put 'presences_update' => 'presence#update'
  get 'student/edit' => 'students#edit'
  get 'faq' => 'students#faq'
  patch 'student/solution' => 'students#solution'
  get 'student/challenge' =>'students#challenge'
  get 'student/chosechallenge' =>'students#chosechallenge'
  get 'student/challengeodp' =>'students#challengeodp'
  get 'student/challengeodp2' =>'students#challengeodp2'
  get 'student/challengeinbox' =>'students#challengeinbox'
  post 'student/challengeconfirm' =>'students#challengeconfirm'
  post 'student/challengeconfirm2' =>'students#challengeconfirm2'
  get 'challenges' => 'challenge#index'
  post 'challenge_win' => 'challenge#win'
  post 'challenge_draw' => 'challenge#draw'
  get 'student/surender' =>  'students#surender'
  get 'student/studentprofile' =>  'students#studentprofile'
  get 'student/hppotion' =>  'students#hppotion'
  get 'contact', to: 'my_mail#new', as: 'contact'
  post 'contact', to: 'my_mail#create'
  get 'settings' => 'students#settings'
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :teacher
  has_many :students
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :correct_teacher, only: [:index, :show, :edit, :update, :destroy]
  # GET /groups
  # GET /groups.json
  def index
    teacher = Teacher.find(curent_user_id)
    @group= teacher.groups.build
    @groups = Group.where(teacher_id: params[:teacher_id])
    @students = Student.joins(:progre).order('points DESC').where(group_id: @groups) #Student.where(group_id:  @groups, :joins => :progre, :order => 'progre.points')
    @lp=0
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @student = @group.students.build
    @students = Student.joins(:progre).order('points DESC').where(group_id: params[:id])
    @classes = Classescalendar.where(group_id: params[:id])
    @nr=0
  end


  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    teacher = Teacher.find(curent_user_id)
    @group = teacher.groups.create(group_params)
    6.times do |class_nr|
      meeting_date_start = Time.now + (7.days * class_nr)
      meeting_date_end = meeting_date_start + (120+15)*60 # 1,5h w sekundach
      meeting = Classescalendar.new(group_id: @group.id, classes_number: class_nr+=1,start: meeting_date_start, end: meeting_date_end)
      meeting.save
    end
    respond_to do |format|
      if @group.save
        format.html { redirect_to teacher_groups_path(session[:user_id]), notice: 'Group was successfully created.' }
        format.json { render :index, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to teacher_groups_path(session[:user_id]), notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :date, :teacher_id)
    end
    def correct_teacher
      if !params[:id].nil? 
        set_group
        redirect_to :back unless Teacher.find(@group.teacher_id) == Teacher.find_by(login: session[:login])
      else
        redirect_to root_url unless logged_as_teacher?
      end
    end
    
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_fields.html.erb
<p>
  <%= f.label :start %><br />
  <%= f.datetime_field :start %>
</p>
<p>
  <%= f.label :end %><br />
  <%= f.datetime_field :end %>
</p>

app/views/groups/_form.html.erb
<%= form_for([@group.teacher, @group]) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name,"Nazwa" %><br>
    <%= f.text_field :name, :class => "form-control", :placeholder => "Nazwa Grupy" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Stwórz Grupę", :class =>"btn btn-primary"%>
  </div>
<% end %>

app/views/groups/_new_student.html.erb
<h1>Dodaj nowego studenta</h1>
<%= form_for @student, url: group_students_path(params[:id]) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this grupy from being saved:</h2>
      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%=f.label :Nr_albumu %>
    <%=f.text_field :album_number, :class => "form-control", :placeholder => "Nr_albumu" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Dodaj studenta", :class =>"btn btn-primary"%>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Edycja Grupy</h1>

<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nazwa"%><br>
    <%= f.text_field :name, :class => "form-control", :placeholder => "Nazwa Grupy"  %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Edytuj", :class =>"btn btn-primary" %>
  </div>
<% end %>

app/views/groups/index.html.erb
<div class="row">
  <div class="col-lg-5">
    <h1>Grupy</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Nazwa</th>
          <th colspan="4"></th>
        </tr>
      </thead>
      <tbody>
        <% @groups.order(:created_at).each do |group| %>
          <tr>
            <td><%= group.name %></td>
            <td><%= link_to 'Pokaż', group, :class => "btn btn-primary", :role =>"button" %></td>
            <td><%= link_to 'Edytuj', edit_group_path(group), :class =>"btn btn-info", :role =>"button"%></td>
            <td><%= link_to 'Usuń', group, method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć grupę?' }, :class => "btn btn-danger", :role =>"button" %></td>
            <td><%= link_to 'Napisz', new_message_path(:idg => group.id), :class =>"btn btn-default", :role =>"button" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <h3>Stwórz nową grupę</h3>
    <%= render 'form'%>
  </div>
  <div class="col-lg-7">
    <h1>Ranking Światowy</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Lp.</th>
          <th>Pkt rankingowe</th>
          <th>Imię</th>
          <th>Nazwisko</th>
          <th>Nr albumu</th>
          <th>Grupa</th>
          <th colspan="4"></th>
        </tr>
      </thead>
      <tbody>
        <% @students.each do |student|%>
          <tr>
            <td><%=@lp += 1%></td>
            <td><%= student.progre.points%></td>
            <td><%= student.name %></td>
            <td><%= student.lastname %></td>
            <td><%= student.album_number%></td>
            <td><%= student.group.name%></td>
            <td><%= link_to 'Pokaż', student_studentprofile_path(student, :results => "1"), :class => "btn btn-primary" %></td>
            <td><%= link_to 'Edytuj', edit_student_path(student), :class =>"btn btn-info" %></td>
            <td><%= link_to 'Usuń', student, method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć studenta?' }, :class =>"btn btn-danger" %></td>
            <td><%= link_to 'Napisz', new_message_path(:iid => student.id), :class =>"btn btn-default" %></td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<!--RANKING GRUPOWY-->
<div class="row">
  <div class="col-lg-12">
    <h1>Ranking Grupowy</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Lp.</th>
          <th>Pkt rankingowe</th>
          <th>Imię</th>
          <th>Nazwisko</th>
          <th>Nr albumu</th>
          <th>E-mail</th>
          <th colspan="4"></th>
          <th>Obecność</th>
        </tr>
      </thead>
      <tbody>
      <%= form_for :presence, :url => presences_update_path, :html => { :method => :put } do %>
        <% @students.each do |student| %>
          <tr>
            <td><%=@nr+=1%></td>
            <td><%=student.progre.points%></td>
            <td><%= student.name %></td>
            <td><%= student.lastname %></td>
            <td><%= student.album_number %></td>
            <td><%= student.email %></td>
            <td><%= link_to 'Pokaż', student_studentprofile_path(student, :results => "1"), :class => "btn btn-primary" %></td>
            <td><%= link_to 'Edytuj', edit_student_path(student), :class =>"btn btn-info" %></td>
            <td><%= link_to 'Usuń', student, method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć studenta?'}, :class =>"btn btn-danger" %></td>
            <td><%= link_to 'Napisz', new_message_path(:iid => student.id), :class =>"btn btn-default" %></td>
            <td>
              <% @presence = Presence.where(student_id: student.id) %>
              <% @presence.each do |presence| %>
                <%= fields_for "presence[]", presence do |presence_fields| %>
                  <%= presence_fields.check_box :present, :class =>"checkbox-inline" %>
                <%end%>
              <%end%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="actions">
      <%= submit_tag "Zapisz obecności", :class =>"btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>


<div class="row">
  <div class="col-lg-7">
    <h1><%= @group.name %></h1>
    <h4>Daty spotkań</h4>
    <%= form_for :clas, :url => classes_update_path, :html => { :method => :put} do %>
      <table class="table table-striped">
        <tr>
          <th>Lekcja</th>
          <th>Start</th>
          <th>Koniec</th>
        </tr>
        <% @classes.each do |clas| %>
          <%= fields_for "clas[]", clas do |clas_fields| %>
          <tr>
            <td><%= clas.classes_number %></td>
            <td><%= clas_fields.datetime_select :start, :class => "form-control datetimepicker4"%> </td>
            <td><%= clas_fields.datetime_select :end %></td>
            <script type="text/javascript">
              $(function () {
                  $('.datetimepicker4').datetimepicker();
              });
            </script>
          </tr>
          <%end%>
        <%end%>
      </table>
      <div class="actions">
        <%= submit_tag "Zachowaj zmiany", :class =>"btn btn-primary"%>
      </div>
    <%end%>
    
  </div>
  <div class="col-lg-5">
    <%=render 'new_student' %>
  </div>
</div>