config/routes.rb
Rails.application.routes.draw do

  resources :sqanswers
  resources :sqresults
  get 'presence/update'
  get 'lesson' => 'exercises#lesson'
  post 'lesson' => 'exercises#lesson'
  post 'new_result' => 'result#create'
  
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'
  resources :sidequests
  root 'session#index'
  resources :answers
  resources :messages
  resources :teachers do
    resources :groups, shallow: true do
      resources :students
    end
    resources :exercises, shallow: true
  end

  get 'show_exe' => 'exercises#show_exe'
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'
  put 'sqanswer_update' => 'sidequests#sqanswer_update'
  put 'classes_update' => 'classescalendar#update'
  put 'presences_update' => 'presence#update'
  get 'student/edit' => 'students#edit'
  get 'faq' => 'students#faq'
  patch 'student/solution' => 'students#solution'
  get 'student/challenge' =>'students#challenge'
  get 'student/chosechallenge' =>'students#chosechallenge'
  get 'student/challengeodp' =>'students#challengeodp'
  get 'student/challengeodp2' =>'students#challengeodp2'
  get 'student/challengeinbox' =>'students#challengeinbox'
  post 'student/challengeconfirm' =>'students#challengeconfirm'
  post 'student/challengeconfirm2' =>'students#challengeconfirm2'
  get 'challenges' => 'challenge#index'
  post 'challenge_win' => 'challenge#win'
  post 'challenge_draw' => 'challenge#draw'
  get 'student/surender' =>  'students#surender'
  get 'student/studentprofile' =>  'students#studentprofile'
  get 'student/hppotion' =>  'students#hppotion'
  get 'contact', to: 'my_mail#new', as: 'contact'
  post 'contact', to: 'my_mail#create'
  get 'settings' => 'students#settings'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :student
end

app/models/awarded_medal.rb
class AwardedMedal < ActiveRecord::Base
    belongs_to :student
    belongs_to :medal
    validates :student_id, presence: true
    validates :medal_id, presence: true
end

app/models/drawnexercise.rb
class Drawnexercise < ActiveRecord::Base
  belongs_to :student
  belongs_to :exercise
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :teacher
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :teacher
  has_many :students
end

app/models/medal.rb
class Medal < ActiveRecord::Base
  has_many :awarded_medals
end

app/models/message.rb
class Message < ActiveRecord::Base
    belongs_to :teacher
    belongs_to :student
end

app/models/my_mail.rb
class MyMail < ActiveRecord::Base
      include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attr_accessor :name, :email, :content

  validates :name,
    presence: true

  validates :email,
    presence: true

  validates :content,
    presence: true
end

app/models/presence.rb
class Presence < ActiveRecord::Base
  belongs_to :student
end

app/models/progre.rb
class Progre < ActiveRecord::Base
  belongs_to :student
  before_update :zerohp
  def expe
    if self.total == 0
      return 0
    else
      self.gained_points.to_d/self.total.to_d
    end
  end
  
  def place_group_ranking
    students_in_group = self.student.group.students.joins(:progre).order('points DESC')
    i=0
    students_in_group.each do |student|
      i+=1
      return i if student == self.student
    end
  end
  
  def place_world_ranking
    students = Student.all.joins(:progre).order('points DESC')
    i=0
    students.each do |student|
      i+=1
      return i if student == self.student
    end
  end
  private
      def zerohp
        if self.hp<=0
          self.hp=40
          self.gained_points=self.gained_points*0.75 
          Message.create!(subject: "Zginąłeś",  
                content: "Zginąłeś. Kontynuujesz grę tracąc 1/4 wszystkich punktów.",
                read: false,
                direction: 0,
                student_id: self.id
               )
        end
      end
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :student
  belongs_to :exercise
end

app/models/sidequest.rb
class Sidequest < ActiveRecord::Base
  belongs_to :teacher
end

app/models/sqanswer.rb
class Sqanswer < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :student
  belongs_to :sidequest
  
  def time
    self.updated_at.to_i - self.created_at.to_i
  end
end

app/models/sqresult.rb
class Sqresult < ActiveRecord::Base
  belongs_to :student
  belongs_to :sidequest
end

app/models/story.rb
class Story < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :group
  has_one :teacher, through: :group
  has_many :presences, dependent: :destroy
  has_one :progre, dependent: :destroy
  has_many :drawnexercises, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :awarded_medals, dependent: :destroy
  has_secure_password
  before_save :downcase_email
  

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }, allow_nil:true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil:true 
  validates :album_number, :numericality => {:only_integer => true}
  def admit_medal(medal)
    awarded_medals.create(medal_id: medal)
    self.progre.points += Medal.find_by(id: medal).value
    self.progre.save
  end
  def take_medal(medal)
    awarded_medals.find_by(medal_id: medal).destroy
  end
  def has_medal?(medal)
    awarded_medals.exists?(medal_id: medal)
  end
  
    private
      def downcase_email
        if !self.email.nil?
          self.email = email.downcase
        end
      end
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
    has_many :groups
    has_many :students, through: :groups
    has_many :exercises
    has_secure_password
    before_save :downcase_email
    validates :name, length: { maximum: 50 }
    validates :password, presence: true, length: { minimum: 2 }, allow_nil:true
    
    private
    
      def downcase_email
        self.email = email.downcase if !self.email.nil?
      end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  before_action :correct_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
    
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
      
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :lastname, :login, :password, :email)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/my_mail_helper.rb
module MyMailHelper
end

app/helpers/result_helper.rb
module ResultHelper
    
 def give_a_medal_and_send_message(medal_id, student)
      student.admit_medal(medal_id) unless student.has_medal?(medal_id)
      m = Medal.find(medal_id)
      Message.create!(teacher_id: session[:user_id], student_id: student.id, subject: "Dostałeś nagrodę specjalną !", content: "Właśnie otrzymałeś #{m.description} !", direction: 0,read: false)
 end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Imię" %><br>
    <%= f.text_field :name, :class =>"form-control", :placeholder =>"Imię" %>
  </div>
  <div class="form-group">
    <%= f.label :lastname, "Nazwisko" %><br>
    <%= f.text_field :lastname, :class =>"form-control", :placeholder =>"Nazwisko" %>
  </div>
  <div class="form-group">
    <%= f.label :login ,"Login"%><br>
    <%= f.text_field :login, :class =>"form-control", :placeholder =>"Login" %>
  </div>
  <div class="form-group">
    <%= f.label :password_digest, "Hasło" %> <br>
    <%= f.password_field :password, :class =>"form-control", :placeholder =>"Hasło" %>
  </div>
  <div class="form-group">
  <%= f.label :password_confirmation, "Potwierdź hasło"%> <br>
  <%= f.password_field :password_confirmation, :class =>"form-control", :placeholder =>"Potwierdź hasło" %>
  </div>
  <div class="form-group">
    <%= f.label :email,"E-mail"%><br>
    <%= f.text_field :email, :class =>"form-control", :placeholder =>"e-mail" %>
  </div>
  <div class="form-group">
    <center><%= f.submit "Zmień", :class =>"btn btn-primary btn-lg" %></center>
  </div>
<% end %>

app/views/teachers/_panel.html.erb
<ul class="sidebar-nav">
        <li class="sidebar-brand">
            Data-Base
        </li>
        <li>
            <%= link_to 'Grupy', teacher_groups_path(session[:user_id]) %>
        </li>
        <li>
            <%= link_to 'Ćwiczenia', teacher_exercises_path(session[:user_id]) %>
        </li>
        <li>
            <%= link_to 'Wyzwania', sidequests_path %>
        </li>
        <li>
            <% if Answer.where(teacher_id: session[:user_id], read: false).where.not(solution: nil).count >0%>
                <strong><%= link_to 'Rozwiązania', answers_path, { :style =>"color: #FFE60B;"}%></strong>
            <% else %>
                <%= link_to 'Rozwiązania', answers_path%>
            <% end %>
        </li>
        <li>
            <% if Message.where(teacher_id: session[:user_id], direction: "1", read: false).count >0%>
                <strong><%= link_to 'Wiadomości', messages_path(session[:user_id]), { :style =>"color: #FFE60B;"} %></strong>
            <% else %>
                <%= link_to 'Wiadomości', messages_path(session[:user_id]) %>
            <% end %>
        </li>
        <li>
            <%= link_to 'Edycja', edit_teacher_path(session[:user_id]) %>
        </li>
        <li>
            <%= link_to "Wyloguj", logout_path, method: "delete"%>
        </li>
</ul>

app/views/teachers/edit.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <center><h1>Edycja</h1></center>
    <%= render 'form' %>
  </div>
</div>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>
<p>
  <strong>Lastname:</strong>
  <%= @teacher.lastname %>
</p>